version: '3'

services:
  ROP-front:
    image: ${IMAGE_TAG}-${CI_COMMIT_SHA}
    networks:
      - traefik_net
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.tags=http"
        - "traefik.port=80"
        - "traefik.protocol=http"
        - "traefik.docker.network=traefik_net"
        - "traefik.backend=ROP-front"
        - "traefik.frontend.rule=Host:rop.zjuqsc.com"
networks:
  traefik_net:
    external: true